### PR TITLE
3.6.1 update

### PR DESCRIPTION
**Pull request by benhuff**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by geoHeil** [comment]
cool! Great @benhuff thanks for making the upgrade happen!

**Comment by ajfriend** [comment]
This is great! Thanks for working on this!

Do you all mind if I add something about conda on the `h3-py` `readme.md` and refer to this repo?

**Comment by geoHeil** [comment]
@ajfriend no absolutely not - please spread the word.

**Comment by ajfriend** [comment]
Awesome. Let me know if this looks OK: https://github.com/uber/h3-py/pull/132

**Pull request merged**
