### PR TITLE
OSX-ARM64 manual migration

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I think the problem now is that the wrong python is found (host instead of build):

```
 -- Found PythonInterp: /Users/runner/miniforge3/conda-bld/h3-py_1650777340143/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python (found version "3.10.4")
```

Any idea how to get around this @conda-forge/help-osx-arm64?

**Comment by erykoff** [comment]
I think you need a patch like was used here https://github.com/conda-forge/zfpy-feedstock/blob/main/recipe/meta.yaml

**Comment by geoHeil** [comment]
@conda-forge-admin can you help with getting this package to work with Apple Silicon? I am quite a novice in conda packaging - in particular for different instruction set architectures

**Comment by mariusvniekerk** [comment]
probably worth reattempting this fresh now that main contains the needed scikit-build dep

**Comment by geoHeil** [comment]
@conda-forge-linter rerender

**Comment by geoHeil** [comment]
@mariusvniekerk how can I trigger the re-render?

**Comment by erykoff** [comment]
@conda-forge-admin please rerender

**Comment by geoHeil** [comment]
Thanks for helping with the re-render!

However, https://dev.azure.com/conda-forge/feedstock-builds/_build?definitionId=8433&view=runs is showing builds several months if not years old and when clicking on details, only invalid links show up - I cannot retrieve the raw logs of the failed pipelines. Only get a pipeline not found error

**Comment by erykoff** [comment]
@conda-forge-admin please restart ci

**Comment by geoHeil** [comment]
I still keep getting the build not found error (even after the fresh rebuild)

**Comment by erykoff** [comment]
It hasn't done a rebuild even though it's supposed to.  I think something is wedged.

**Comment by geoHeil** [comment]
@erykoff who could help to get the build running again?

**Comment by Tobias-Fischer** [comment]
I've merged in the changes from the main branch and rerendered. If someone wants to continue this PR, please let me know and I'm happy to provide write access to my fork.

**Comment by geoHeil** [comment]
at least now the logs are viewable. Great.

```
#ERROR: Failed building wheel for h3
  Building wheel for h3 (pyproject.toml): finished with status 'error'
Failed to build h3
ERROR: Could not build wheels for h3, which is required to install pyproject.toml-based projects
```

If I read this correctly, the native C dependency of H3 does not yet build for ARM is this correct? I.e. condaforge/h3 feedstock would need to be fixed first?

**Comment by zklaus** [comment]
Look like under the hood, this is a cmake build. I would start by turning the embedded build script into an explicit one and then see if one can apply the advise from https://conda-forge.org/docs/maintainer/knowledge_base.html#using-cmake.

**Comment by erykoff** [comment]
Using `scikit-build` and `cmake` in cross compilation is something that is not smooth at the moment.  Something like is done in this feedstock might help? https://github.com/conda-forge/line_profiler-feedstock/blob/main/recipe/meta.yaml. Specifically https://github.com/conda-forge/line_profiler-feedstock/blob/main/recipe/meta.yaml#L16-L22 and https://github.com/conda-forge/line_profiler-feedstock/blob/main/recipe/meta.yaml#L31

**Comment by geoHeil** [comment]
H3 should now have an arm release - just merged the PR with all green tests.

**Comment by geoHeil** [comment]
@conda-forge-admin please restart ci

**Comment by isuruf** [comment]
https://github.com/conda-forge/cross-python-feedstock/pull/66 should fix the error

**Comment by Tobias-Fischer** [comment]
Awesome - looks like this is all green now :)

**Comment by geoHeil** [comment]
Awesome! Many thanks

**Comment by geoHeil** [comment]
Is anyone else experiencing the same issues: https://github.com/conda-forge/h3-py-feedstock/issues/38

**Comment by zaneselvans** [comment]
Yep, still having this problem.

**Pull request merged**
