### PR TITLE
changing sha & removing old maintainers

### PR DESCRIPTION
**Pull request by BubblyOrca**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by geoHeil** [comment]
Great! The SHA change is still missing though.

**Comment by BubblyOrca** [comment]
For sure, I noticed that the sha was already updated along with the version update so I just removed the old maintainers.

**Comment by geoHeil** [comment]
Are you certain that the others should be removed? If yes, we can merge it.

**Comment by BubblyOrca** [comment]
Yes, I was given consent.

**Pull request merged**
