### PR TITLE
Manually migrate to python 3.13

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
I'm not sure why #42 never got recreated by the bot but let's do it manually...

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I'd like to have this for https://github.com/conda-forge/timezonefinder-feedstock/pull/74, since this new release claims to support python 3.13.

**Comment by xylar** [comment]
@conda-forge/h3-py, I'd appreciate you having a look and merging if you can.  This will help me downstream in timezonefinder.

**Comment by geoHeil** [comment]
Let me check - but as CI is green this should be fairly fast

**Review by geoHeil — APPROVED** [review]

**Comment by xylar** [comment]
Wow, thanks so much @geoHeil!  That was much faster than I expected to get a response!

I reported the issue that the bot didn't make a new PR:
https://github.com/regro/cf-scripts/issues/3026

**Pull request merged**
