### PR TITLE
Use workaround for buggy scikit-build to fix osx-arm64 builds + bump 3.7.6

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Using the workaround from https://github.com/conda-forge/slycot-feedstock/pull/47 (credits @isuruf) to fix #38

**Comment by Tobias-Fischer** [comment]
Seems like this workaround doesn’t work here ..

**Comment by nelsonauner** [comment]
@Tobias-Fischer Any thoughts on what current h3-py conda users should use?

**Comment by Tobias-Fischer** [comment]
Unfortunately not. Maybe @conda-forge/help-osx-arm64 do you have a hint on how to tackle this?

**Comment by erykoff** [comment]
@conda-forge-admin, please restart ci

**Comment by erykoff** [comment]
Trying to rebuild with latest scikit-build which should have fixed the linking problems...?

**Comment by erykoff** [comment]
@conda-forge-admin, please restart ci

**Comment by erykoff** [comment]
Ok with scikit-build=0.17 this builds. It is my belief that it should also work now but I haven’t tested the binary.

**Comment by Tobias-Fischer** [comment]
Ah nice. I guess we don’t need to the workaround then?

**Comment by geoHeil** [comment]
agreed! LGTM. Lets merge/publish.

**Comment by geoHeil** [comment]
> Ah nice. I guess we don’t need to the workaround then?

So we can merge this branch and solve the problem for good? Or do we need a separate PR to use the latest tools and then move on?

**Comment by Tobias-Fischer** [comment]
I don’t have any objections to merging - we can see how we go.

I guess the proper way would be to store the build artefacts and try before merging though. But seeing that things are already broken, the situation can’t get worse ..

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin please rerender

**Pull request merged**
